// ----------------------------------------------------------
// Sites
new Site("Google", "https://google.com", "g.jpg");
new Site("Bing", "http://bing.com/", "bing.png");
new Site("DuckDuckGo", "https://duckduckgo.com/", "duckduckgo.png");
new Site("Startpage", "https://www.startpage.com/", "startpage.jpg");
new Site("Facebook", "https://facebook.com", "fb.png");
new Site("X", "https://x.com", "x.png", "X (formerly Twitter)");
new Site("LinkedIn", "https://www.linkedin.com", "li.webp");
new Site("Reddit", "https://reddit.com", "rdi.png");
new Site("Tumblr", "https://tumblr.com", "tumblr.png");
new Site("Bsky", "https://bsky.app", "bsky.png");
new Site("Medium", "https://medium.com", "medium.png");
new Site("Quora", "https://www.quora.com", "qra.png");
new Site("Pinterest", "https://www.pinterest.com", "pt.png");
new Site("Instagram", "https://instagram.com", "ig.png");
new Site("YouTube", "https://youtube.com", "yt.png");
new Site("Tik Tok", "https://www.tiktok.com/", "tiktok.png");
new Site("Vimeo", "https://vimeo.com/", "vimeo.jpg");
new Site("Twitch", "https://www.twitch.tv/", "twitch.jpg");
new Site("PeerTube", "https://joinpeertube.org/", "peertube.svg");
new Site("imgur", "https://imgur.com/", "imgur.png");
new Site("GIPHY", "https://giphy.com/", "giphy.png");
new Site("SoundCloud", "https://soundcloud.com", "sc.png");
new Site("Spotify", "https://www.spotify.com/", "spotify.jpg");
new Site("Netflix", "https://www.netflix.com/", "netflix.jpg");
new Site("OpenStreetMap", "https://www.openstreetmap.org/", "openstreetmap.svg");
new Site("WhatsApp", "https://web.whatsapp.com", "wa.png");
new Site("Telegram", "https://web.telegram.org", "teleg.jpg");
new Site("Messenger", "https://www.messenger.com", "m.png", "Facebook Messenger");
new Site("Signal", "https://signal.org/", "signal.png");
new Site("Wire", "https://wire.com/", "wire.png");
new Site("Threema", "https://threema.ch", "threema.png");
new Site("Wickr", "https://wickr.com/", "wickr.png");
new Site("Skype", "https://skype.com", "sp.png");
new Site("Snapchat", "https://www.snapchat.com/", "snapchat.jpg");
new Site("Discord", "https://discord.com/", "discord.jpg");
new Site("Zoom", "https://zoom.us/", "zoom.jpg");
new Site("Teams", "https://teams.microsoft.com", "teams.png", "Microsoft Teams");
new Site("Gmail", "https://mail.google.com", "gm.png");
new Site("ProtonMail", "https://protonmail.com/", "proton.jpg");
new Site("Outlook", "https://outlook.live.com/", "outlook.png");
new Site("Yahoo Mail", "https://mail.yahoo.com/", "yahoomail.png");
new Site("Disroot", "https://disroot.org/en/services/email", "disroot.png");
new Site("Tutanota", "https://tutanota.com/", "tutanota.png");
new Site("Play Store", "https://play.google.com", "gps.png");
new Site("G. Translate", "https://translate.google.com", "gt.png", "Google Translator");
new Site("Translate.com", "https://www.translate.com/", "translatecom.png");
new Site("Lingva", "https://lingva.ml/", "lingva.svg");
new Site("LibreTranslate", "https://libretranslate.com/", "libre-tr.png");
new Site("DeepL", "https://www.deepl.com/en/translator", "deepl.jpg");
new Site("B. Translator", "https://www.bing.com/translator", "bingtrans.png", "Bing Translator");
new Site("G. Maps", "https://maps.google.com", "gms.png", "Google Maps");
new Site("Drive", "https://drive.google.com", "d.png", "Google Drive");
new Site("OneDrive", "https://onedrive.live.com/", "onedrive.png");
new Site("iCloud", "https://www.icloud.com/", "icloud.png");
new Site("Dropbox", "https://www.dropbox.com/", "dropbox.png");
new Site("Nextcloud", "https://nextcloud.com/", "nextcloud.png");
new Site("Filen", "https://filen.io/", "filen.png");
new Site("Sync.com", "https://www.sync.com/", "synccom.jpeg");
new Site("pCloud", "https://www.pcloud.com/", "pcloud.png");
new Site("MEGA", "https://mega.nz/", "mega.png");
new Site("WeTransfer", "https://wetransfer.com/", "wet.png");
new Site("WikiPedia", "https://wikipedia.com", "wp.png");
new Site("GitHub", "https://github.com/", "github.png");
new Site("ONLYOFFICE", "https://www.onlyoffice.com/", "onlyoffice.svg");
new Site("PrivateBin", "https://privatebin.info/", "privatebin.svg");
new Site("CryptPad", "https://cryptpad.fr/pad/", "cryptpad.svg");
new Site("Bitwarden", "https://bitwarden.com/", "bitwarden.svg");
new Site("Hat.sh", "https://hat.sh/", "hatsh.png");
new Site("Mastodon", "https://joinmastodon.org/", "mastodon.svg");
new Site("diaspora*", "https://diasporafoundation.org/", "diaspora.svg");
new Site("Friendica", "https://friendi.ca/", "friendica.svg");
new Site("PixelFed", "https://pixelfed.org/", "pixelfed.svg");
new Site("Standard Notes", "https://app.standardnotes.com/", "stdnotes.svg");
// ----------------------------------------------------------